development:
  url: redis://localhost:6379/0
  host: localhost
  port: 6379
  db: 1

test:
  url: redis://localhost:6378/0
  host: localhost
  port: 6378
  db: 1

staging:
  url: redis://localhost:6379/0
  host: localhost
  port: 6379
  db: 1

production:
  url: redis://localhost:6379/0
  host: localhost
  port: 6379
  db: 1