default: &default
  source_path: app/assets
  source_entry_path: javascripts
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths:
  - /Users/qin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activestorage-6.0.0/app/assets/javascripts
  - /Users/qin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/app/assets/javascripts
  - /Users/qin/work/ruby/default_form/app/assets/javascripts
  - /Users/qin/work/engine/rails_com/app/assets/javascripts
  - /Users/qin/work/engine/rails_log/app/assets/javascripts
  - /Users/qin/work/engine/rails_org/app/assets/javascripts
  - /Users/qin/work/engine/rails_profile/app/assets/javascripts
  - /Users/qin/work/engine/rails_auth/app/assets/javascripts
  - /Users/qin/work/engine/rails_role/app/assets/javascripts
  - /Users/qin/work/engine/rails_data/app/assets/javascripts
  - /Users/qin/work/engine/rails_detail/app/assets/javascripts
  - /Users/qin/work/engine/rails_notice/app/assets/javascripts
  - /Users/qin/work/engine/rails_audit/app/assets/javascripts
  - /Users/qin/work/engine/rails_trade/app/assets/javascripts
  - /Users/qin/work/engine/rails_factory/app/assets/javascripts
  - /Users/qin/work/engine/rails_taxon/app/assets/javascripts
  - /Users/qin/work/engine/rails_booking/app/assets/javascripts
  - /Users/qin/work/engine/rails_wechat/app/assets/javascripts
  - /Users/qin/work/engine/rails_bench/app/assets/javascripts
  - /Users/qin/work/engine/rails_vip/app/assets/javascripts
  - /Users/qin/work/engine/rails_crm/app/assets/javascripts
  cache_manifest: false
  extract_css: false
  static_assets_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .tiff
  - .ico
  - .svg
  - .eot
  - .otf
  - .ttf
  - .woff
  - .woff2
  extensions:
  - .mjs
  - .js
  - .sass
  - .scss
  - .css
  - .module.sass
  - .module.scss
  - .module.css
  - .png
  - .svg
  - .gif
  - .jpeg
  - .jpg
development:
  <<: *default
  compile: true
  check_yarn_integrity: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/
test:
  <<: *default
  compile: true
  public_output_path: packs-test
production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
